packages:
  linux:
    - name: build-essential
    - name: age
    - name: pcscd
    - name: unzip
    - name: git
    - name: fzf
    - name: neovim
    - name: ripgrep
    - name: tmux
    - name: wget
    - name: zsh
    - name: jq
    - name: screen
    - name: dnsutils
    - name: tree
    - name: xq
    - name: zlib1g-dev
  darwin:
    brews:
    - 'git'
    - 'fzf'
    - 'neovim'
    - 'ripgrep'
    - 'tailscale'
    - 'tfenv'
    - 'tmux'
    - 'wget'
    - 'xclip'
    - 'xq'
    - 'xz'
    - 'colima'
    - 'tree'
    - 'carlocab/personal/unrar'
    - 'jless'
    #- 'fastly/tap/fastly'
    casks:
    - 'font-hack-nerd-font'
    - 'balenaetcher'
    - 'thonny'
    - 'signal'
    - 'vlc'
    - 'rectangle'
    - 'spotify'
    - 'keybase'
    - 'obsidian'
