[tools]
awscli = "latest"
aws-vault = "latest"
direnv = "latest"
helm = "latest"
k9s = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
kubent = "latest"
kustomize = "latest"
nomad = "latest"
pre-commit = "latest"
talosctl = "1.6.7"
vault = "latest"
viddy = "latest"
yq = "latest"
